name: 'Clang Format Multi-Version'
description: 'Format C/C++ code with multiple clang-format versions and auto-commit changes'
author: 'pachadotdev'

branding:
  icon: 'code'
  color: 'blue'

inputs:
  version:
    description: 'Clang-format version to use (11-19)'
    required: false
    default: '19'
  
  files:
    description: 'Files or patterns to format (default: all C/C++ files)'
    required: false
    default: ''
  
  auto-commit:
    description: 'Auto-commit formatted changes'
    required: false
    default: 'true'
  
  commit-message:
    description: 'Commit message for auto-commit'
    required: false
    default: 'style: auto-format code with clang-format'
  
  fail-on-diff:
    description: 'Fail the action if formatting changes are needed'
    required: false
    default: 'false'
  
  working-directory:
    description: 'Working directory to run clang-format in'
    required: false
    default: '.'

outputs:
  files-changed:
    description: 'Number of files that were changed'
    value: ${{ steps.format.outputs.files-changed }}
  
  has-changes:
    description: 'Whether any files were changed'
    value: ${{ steps.format.outputs.has-changes }}

runs:
  using: 'composite'
  steps:
    - name: Setup clang-format
      shell: bash
      run: |
        echo "🚀 Setting up clang-format-${{ inputs.version }}"
        
        # Create binary directory
        mkdir -p /tmp/clang-format-bin
        
        # Download clang-format binaries
        RELEASE_URL="https://github.com/pachadotdev/clang-format/releases/download/v0.1/clang-format.tar.gz"
        echo "📥 Downloading clang-format binaries..."
        
        cd /tmp
        curl -L -o clang-format.tar.gz "$RELEASE_URL"
        tar -xzf clang-format.tar.gz -C clang-format-bin
        chmod +x clang-format-bin/clang-format*
        
        # Add to PATH
        echo "/tmp/clang-format-bin" >> $GITHUB_PATH
        
        # Verify installation
        if [ -f "/tmp/clang-format-bin/clang-format-${{ inputs.version }}" ]; then
          echo "✅ clang-format-${{ inputs.version }} installed successfully"
          /tmp/clang-format-bin/clang-format-${{ inputs.version }} --version
        else
          echo "❌ clang-format-${{ inputs.version }} not found"
          echo "Available versions:"
          ls -la /tmp/clang-format-bin/
          exit 1
        fi

    - name: Format code
      id: format
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "🎨 Formatting code with clang-format-${{ inputs.version }}"
        
        # Store git status before formatting
        git status --porcelain > /tmp/git-status-before
        
        # Determine files to format
        if [ -n "${{ inputs.files }}" ]; then
          echo "Formatting specified files/patterns: ${{ inputs.files }}"
          FILES="${{ inputs.files }}"
        else
          echo "Finding all C/C++ files..."
          FILES=$(find . -type f \( -name '*.cpp' -o -name '*.hpp' -o -name '*.c' -o -name '*.h' -o -name '*.cc' -o -name '*.cxx' -o -name '*.hxx' \) 2>/dev/null | head -100)
        fi
        
        if [ -z "$FILES" ]; then
          echo "No C/C++ files found to format"
          echo "files-changed=0" >> $GITHUB_OUTPUT
          echo "has-changes=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Format files
        FILES_CHANGED=0
        for file in $FILES; do
          if [ -f "$file" ]; then
            echo "  📄 Formatting: $file"
            /tmp/clang-format-bin/clang-format-${{ inputs.version }} -i "$file"
            if ! git diff --quiet "$file"; then
              FILES_CHANGED=$((FILES_CHANGED + 1))
            fi
          fi
        done
        
        # Check for changes
        git status --porcelain > /tmp/git-status-after
        
        if ! cmp -s /tmp/git-status-before /tmp/git-status-after; then
          echo "has-changes=true" >> $GITHUB_OUTPUT
          echo "files-changed=$FILES_CHANGED" >> $GITHUB_OUTPUT
          echo "✨ Formatted $FILES_CHANGED file(s)"
          
          # Show diff summary
          echo ""
          echo "📊 Changes summary:"
          git diff --stat
          
        else
          echo "has-changes=false" >> $GITHUB_OUTPUT
          echo "files-changed=0" >> $GITHUB_OUTPUT
          echo "✅ No formatting changes needed"
        fi

    - name: Auto-commit changes
      if: steps.format.outputs.has-changes == 'true' && inputs.auto-commit == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "📝 Auto-committing formatted changes"
        
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action (clang-format)"
        
        # Add and commit changes
        git add .
        git commit -m "${{ inputs.commit-message }}"
        
        # Push changes
        git push
        
        echo "✅ Changes committed and pushed"

    - name: Check for required changes
      if: inputs.fail-on-diff == 'true' && steps.format.outputs.has-changes == 'true'
      shell: bash
      run: |
        echo "❌ Code formatting issues detected!"
        echo "The following files need formatting:"
        git diff --name-only
        echo ""
        echo "Please run clang-format on your code before committing."
        exit 1
